"""
Django settings for karisha_pm project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'karisha_pm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'karisha_pm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Для авто-модерации отзывов через AI
MISTRAL_API_KEY = os.getenv('MISTRAL_API_KEY')
MISTRAL_MODEL = os.getenv('MISTRAL_MODEL')

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
YOUR_PERSONAL_CHAT_ID = os.getenv('YOUR_PERSONAL_CHAT_ID')



# Настройки Jazzmin
JAZZMIN_SETTINGS = {
    # Заголовок на странице входа (по умолчанию: "Django Administration")
    "site_header": 'Салон красоты "Karisha_PM"',
    
    # Заголовок на главной странице админки (по умолчанию: "Site Administration")
    "site_brand": 'Karisha_PM',
    
    # Логотип для вашего сайта, должен быть в статических файлах
    "site_logo": "images/logo.png",
    
    # Логотип для страницы входа (по умолчанию: None)
    "login_logo": None,
    
    # Логотип для страницы входа (маленький) (по умолчанию: None)
    "login_logo_dark": None,
    
    # CSS-класс, который применяется к логотипу
    "site_logo_classes": "img-circle",
    
    # Относительный путь к значку, который будет отображаться рядом с именем на странице администратора
    "site_icon": None,
    
    # Приветственный текст на странице входа
    "welcome_sign": "Добро пожаловать в панель администратора",
    
    # Авторские права
    "copyright": 'Салон красоты "Karisha_PM" © 2024',
    
    # Ссылка на главную страницу сайта
    "site_url": "/",
    
    # Модель пользователя (по умолчанию: auth.User)
    "user_model": "auth.User",
    
    # Скрыть приложения из списка приложений (по умолчанию: [])
    "hide_apps": [],
    
    # Скрыть модели из списка моделей (по умолчанию: [])
    "hide_models": [],
    
    # Список приложений (и/или моделей), которые будут отображаться в верхней части бокового меню
    # (по умолчанию: [])
    "order_with_respect_to": ["core"],
    
    # Пользовательские ссылки для добавления в боковое меню
    "custom_links": {
        # Ссылка для всех приложений
        "__all__": [{
            "name": "Статистика салона", 
            "url": "admin_dashboard", 
            "icon": "fas fa-chart-line",
        }],
        # Существующие ссылки для приложения core
        "core": [{
            "name": "Вернуться на сайт", 
            "url": "/", 
            "icon": "fas fa-home",
        }]
    },
    
    # Пользовательские значки для приложений/моделей
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Master": "fas fa-user-md",
        "core.Service": "fas fa-concierge-bell",
        "core.Visit": "fas fa-calendar-check",
        "core.Review": "fas fa-comment",
    },
    
    # Значки из FontAwesome (по умолчанию: {"auth": "fas fa-users-cog"})
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Использовать ли UI с вкладками, False - использовать старый UI (по умолчанию: True)
    "use_google_fonts_cdn": True,
    
    # Показывать ли пользовательские кнопки действий на всех страницах списка (по умолчанию: False)
    "show_ui_builder": False,
    
    # Изменить связанные модальные окна (по умолчанию: {"auth.user": {"title": "User"}})
    "related_modal_active": True,
    
    # Настройки UI
    "changeform_format": "horizontal_tabs",  # horizontal_tabs (по умолчанию) или vertical_tabs
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # Настройки темы
    "theme": "default",  # default, slate, darkly, solar, superhero
    "dark_mode_theme": "darkly",
    "custom_css": None,
    "custom_js": None,
    
    # Добавляем пункт в верхнее меню
    "topmenu_links": [
        # Ссылка на главную страницу админки
        {"name": "Главная", "url": "admin:index"},
        
        # Ссылка на дашборд
        {"name": "Статистика", "url": "admin_dashboard"},
        
        # Ссылка на сайт
        {"name": "Сайт", "url": "/", "new_window": True},
    ],
}

# Настройки UI для Jazzmin
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-pink",
    "accent": "accent-pink",
    "navbar": "navbar-pink navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-pink",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
